# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SA2_118bis_Tdoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdoc_number', models.CharField(max_length=12)),
                ('tdoc_title', models.CharField(max_length=120)),
                ('tdoc_source', models.CharField(max_length=60)),
                ('tdoc_type', models.CharField(max_length=10)),
                ('tdoc_agendaitem', models.CharField(max_length=10)),
                ('tdoc_ai_description', models.CharField(max_length=40)),
                ('tdoc_status', models.CharField(max_length=10)),
                ('tdoc_revision_of', models.CharField(max_length=10)),
                ('tdoc_revised_to', models.CharField(max_length=10)),
                ('tdoc_release', models.CharField(max_length=10)),
                ('tdoc_workitem', models.CharField(max_length=16)),
            ],
        ),
    ]
