# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdocsonline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sa2_118bis_tdoc',
            name='id',
        ),
        migrations.AlterField(
            model_name='sa2_118bis_tdoc',
            name='tdoc_number',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
